name: Terraform

on:
  - push
  - workflow_dispatch

jobs:
  github:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/github

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check formatting
        run: terraform fmt -check

      - name: Initialize a working directory
        run: terraform init

      - name: Validate the configuration files
        run: terraform validate

      - name: Create an execution plan
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: terraform plan

      - name: Apply the changes
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform apply -auto-approve

  scaleway:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/scaleway

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check formatting
        run: terraform fmt -check

      - name: Initialize a working directory
        run: terraform init

      - name: Validate the configuration files
        run: terraform validate

      - name: Create an execution plan
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: terraform plan

      - name: Apply the changes
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform apply -auto-approve
